name: Send to Suprise Santa Ubuntu

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    environment:
      name: production

    steps:
      - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '18.x'
      - name: Decrypt files
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase=${{ secrets.PASSPHRASE }} --output .env .doings.gpg
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: Install dependencies
        run: npm install
      - name: Apply updates
        run: npm run apply.updates
      # - name: Start Application
      #   run: pm2 restart
